= Infragistics Topic Templates

This repository includes AsciiDoc topic templates intended to be used with link:https://github.com/Infragistics/livewire[Livewire] for writing link:http://www.infragistics.com/support/online-documentation[Infragistics help documentation].

The purpose of the templates are to provide a starting point as you write product documentation. You may not use all sections and are expected to change the contents of the file from the template to best suit the content. In other words let the content you are writing about lead to toward the best topic structure rather than worrying about adhering to a document structure.

== Templates
The templates included in this repository are:

- link:general.adoc[General]
- link:adding.adoc[Adding]
- link:breaking-changes.adoc[Breaking Changes]
- link:landing-page.adoc[Landing Page]
- link:user-interactions-and-usability.adoc[User Interactions and Usability]
- link:visual-elements.adoc[Visual Elements]
- link:whats-new.adoc[What's New]

== Using the Templates

To use the templates you simply need to clone this repository:

    git clone https://github.com/Infragistics/topic-templates.git

And then copy the template you want to work with into a separate location each time you want to us it.